CFLAGS=-Wall -Wextra -Wpedantic -O2
CC=armv7l-linux-musleabihf-gcc
LDFLAGS=-static

2.2.3progt: 2.2.3progt.o 2.2.3progtmain.o

2.3.1progt: 2.3.1progt.o 2.3.1progtmain.o

2.3.1progs: 2.3.1progs.o 2.3.1progsmain.o

clean:
	rm -f *.o 2.2.3progt 2.3.1progt 2.3.1progs

.PHONY: clean
