</$objtype/mkfile

TARG=genrands
BIN=.
CLEANFILES=2.3.1pool.s `{ls *.mixal *.mix >[2]/dev/null}

</sys/src/cmd/mkmany

2.3.1pool.s:	genrands.install
	genrands > 2.3.1pool.s

2.3.1prog%.mixal:R:	2.3.1pool.s 2.3.1prog%.s 2.3.1prog%main.s
	cat $^ > $@
